from enum import Enum

class ResponseSignals(Enum):
    SUCCESS = "SUCCESS"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    UPLOAD_ERROR = "UPLOAD_ERROR"
    PROCESSING_ERROR = "PROCESSING_ERROR"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"